### ISSUE TITLE
Ambientación y sonidos/músicas

### ISSUE THREAD

**Issue by Xexuline** [OSWeekends/rolgame#10]
Investigación sobre ambientación y sonidos/músicas de librerías de uso libre.

**Comment by tastytune** [comment]
Buena Xexu, por aquí te dejo un canal de Youtube (YMUZ) que tengo con un amiguete, es músiquilla Open Source
https://www.youtube.com/channel/UCxl6wF_r9vO9fKWYugBGzFw

**Comment by eidal** [comment]
Tal vez nos podríamos apoyar en la guild de cultura de OSW, seguro que nos pueden echar una mano al respecto...

**Comment by PabloFMM** [comment]
Este es el sitio de referencia que yo conozco todo creative commons o similar https://freesound.org/ tambien aqui se listan los mas reconocidos https://commons.wikimedia.org/wiki/Commons:Free_media_resources/Sound y esto https://mediacommons.psu.edu/free-media-library/
