### ISSUE TITLE
Definición preguntas para usuarios

### ISSUE THREAD

**Issue by Xexuline** [OSWeekends/rolgame#11]
Definición preguntas para usuarios

**Comment by Vickysolo** [comment]
Copio lo que hablamos acerca de las preguntas en la reunión del 05/04:

**Comment by Vickysolo** [comment]
Las preguntas que hagamos deben ser abiertas, hay que dar conversación y fijarnos bien en qué nos dicen los usuarios y sobre todo en cómo lo dicen.
Lista de preguntas:
Cómo organizas las partidas?
A qué sueles jugar?
Has jugado en Remoto?
Campaña rápida o por capítulos¿
Ambientas las campañas?
Por qué juegas a rol?
Pedir datos
Siempre que nos den pie, preguntar por qué. Si nos dicen que no preguntar por qué.
Sacar el perfil persona: Edad, metas, como son…

**Comment by eidal** [comment]
Una preguntilla, el perfil de persona a la que hacer la entrevista es solo a organizadores de partidas o también a jugadores asiduos? Supongo que tanto de partidas de rol in situ como remotas, verdad?

**Comment by mrcodedev** [comment]
Desde mi punto de vista creo que debería de hacérselo a los dos perfiles, ya que creo que serían usuarios hipotéticos de la posible plataforma (aún no tenemos definido el producto porque estamos en el paso de encontrar una necesidad).
Y de lo segundo me has dejado con la duda, ya que siempre juega in situ, no sé si nos podría dar una opinión de una plataforma online, pero siempre se puede preguntar que le haría pasarse del rol offline al online. ¿Qué pensáis?
