### ISSUE TITLE
Voluntarios para hacer encuestas a jugadores de Rol

### ISSUE THREAD

**Issue by Vickysolo** [OSWeekends/rolgame#13]
A partir del 16/04 iremos a entrevistar a diferentes jugadores de Rol para hacernos una idea de las necesidades de los mismos. Este Issue es para que todos lo que quieran ser voluntarios se apunten:

**Comment by mrcodedev** [comment]
Yo físicamente iré al sitio este que he mencionado en Slack, si alguien me quiere acompañar que lo diga. Aún tengo que cerrar fecha. Ya si hay que ir a otros sitios, decidlo y si me cuadra puedo acompañar. Y si es online, si tengo huecos idem.

**Comment by Xexuline** [comment]
Contad conmigo para ir a hacer preguntas! Tardes, casi todas libres!!

**Comment by teresamadruga** [comment]
También puedo hacer preguntas

**Comment by eidal** [comment]
Yo podría preguntar por la zona de Alicante, pasar por un par de sitios donde organizan partidas... puede ir bien?

**Comment by mrcodedev** [comment]
¿En Ateneo? 😄

**Comment by Vickysolo** [comment]
@eidal sería genial si pudieses preguntar por allí, a más sitios mejor!

Te pego la info de las preuntas:
