### ISSUE TITLE
Hacer resumen de los videos

### ISSUE THREAD

**Issue by ElenaMLopez** [OSWeekends/rolgame#17]
Ver los videos y hacer un resumen de los puntos principales de la entrevista:
Pregunta / Respuesta. Solo puntos fundamentales. Asignado a Jose

**Comment by mrcodedev** [comment]
Realizada la transcripción de la entrevista con Juan Carlos. No sé si la issue estará cerrada. Si es así debemos de cerrarla.

**Comment by ElenaMLopez** [comment]
=)
