### ISSUE TITLE
Añadir a los colaboradores al repo

### ISSUE THREAD

**Issue by Vickysolo** [OSWeekends/rolgame#7]

**Comment by eidal** [comment]
Soy Adel para Back, con este comentario te vale para añadirme? :)

**Comment by luisddm** [comment]
Hola! Lo mismo digo ;)

**Comment by Xexuline** [comment]
Y otro más!

**Comment by Josheriff** [comment]
@eidal @luisddm y @Xexuline añadidos, revisen el correo

**Comment by Tokytome** [comment]
Hola soy Diana. Puedo hacer tareas de diseño, ilustración, front e impresión 3D ...

**Comment by ElenaMLopez** [comment]
Elena here! **Front y maquetación**  es lo que hago habitualmente. También se me da bien redactar. Contad con mi carcaj!!!! :smile_cat:

**Comment by PabloFMM** [comment]
holaaa!! Aqui Pablo contad con mi barita!! Lo mio es la creatividad, en general no se me da mal facilitar cosas a los equipos.

**Comment by baumannzone** [comment]
y0 y0. No se si estoy dentro o no. Por si acaso, aqui me teneis.
![img](https://media1.tenor.com/images/f8d3bb744832ecb22702ab5ca70bcd1b/tenor.gif)

**Comment by letzgar** [comment]
Hola buenas, soy Alejandro, puedo ayudar con el front y un poquito con el back.

**Comment by ValKiriann** [comment]
Hola! yo ya estoy dentro creo, pero por si acaso os cuento. Mi perfil es diseño gráfico y front. Nuestro back en Vue no lo domino.

**Comment by UlisesGascon** [comment]
Añadido todo el mundo hasta aqui ^^

**Comment by mrcodedev** [comment]
Hola soy José Luis. Perfil FullStack, con una impresora 3D.

**Comment by annabranco** [comment]
Holaa... estoy ya añadida como colaboradora? ☺️

**Comment by UlisesGascon** [comment]
@annabranco si estas ^^
