### ISSUE TITLE
Definición Backlog

### ISSUE THREAD

**Issue by Xexuline** [OSWeekends/rolgame#9]
## Reunión para definir el backlog para el primer sprint!!

Se va acercando la fecha de finalización de sprint 0 y necesitamos ver como vamos a dividir tareas, que caminos vamos a empezar a seguir, etc...

- [ ] Revisión de funcionalidades
- [ ] División de tareas
- [ ] Roadmap

**Comment by Xexuline** [comment]
@eidal ahora mismo, el backog en general, cuando nos podamos reunir y ver, dividimos las tareas para back, front etc... (Al menos así me dice mi cabeza que deberíamos hacerlo :stuck_out_tongue: ). Aún no hay casi nada definido y estaría bien empezar a tener algo que tengo ganas de meterle mano al código :smiley:

**Comment by eidal** [comment]
Me parece guay @Xexuline , yo inicialmente estoy viéndome un poco por encima la documentación de pillarjs, no dispondré de mucho tiempo inicialmente para colaborar, pero también tengo ganas de aprender mucho de vosotros :)
